### ISSUE TITLE
error importing nnint and bilint

### ISSUE THREAD

**Issue by lkreidberg** [kevin218/POET#9] opened 2018-12-07 22:53 UTC
Hi Kevin et al. - nice work on this!! I *almost* got everything working in Python 3 without a hitch, but I'm running into one weird issue.

I compiled the c modules using the build.sh script in models_c. There were no compilation errors. However, when I run UnitTest.py I get two errors:

 Bilinint:   FAIL to load
Nnint:      FAIL to load

All the other extensions are fine. Have you run into this, or have any idea what the problem might be?

**Comment by kevin218** [comment] 2018-12-07 23:37
The problem is likely in setup.py. You probably want to run the Darwin set of exec commands.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by lkreidberg** [comment] 2018-12-08 14:51
No dice - setup.py is using Darwin, and the other extension modules work fine (I tested all the way through to fitting a light curve). It's just bilinint and nnint.

I dug a little deeper and I'm finding that the problem occurs on line 33 of bilinint.c:

```
if(!PyArg_ParseTupleAndKeywords(args,keywds,"OO|OOO",kwlist,&ipparams,&posflux\
                                  ,&etc,&retbinflux,&retbinstd))                
    {                                                                           
      return NULL;                                                              
    }     
```

If I comment out the code from line 33 on down, the module imports just fine (it doesn't calculate the correct thing, of course). Maybe the problem is with the optional argument read in as "|"? I'll keep digging...

**Comment by kevin218** [comment] 2018-12-08 15:00
@exowanderer Thoughts?

**Comment by kevin218** [comment] 2018-12-08 23:15
Just installed and tested on my Mac without any problems.  Are you using Clang for your C compiler?

**Comment by lkreidberg** [comment] 2018-12-09 12:55
Yep, I'm using clang. I'm working with the anaconda distribution of python3, and I updated to the new Mac OS (Mojave).

**Comment by kevin218** [comment] 2018-12-09 15:46
I'm still one version back (High Sierra), but I do use anaconda.  

A temporary workaround is to move bilinint.c and nnint.c from `c_code` to  `extras` and move bilinint.py and nnint.py from `extras` to `py_func`.  You'll need to make a pull request first though.  These model components won't run in parallel, but running slowly is better than not at all.

**Comment by lkreidberg** [comment] 2018-12-10 22:26
thanks! I'll give it a try with the python versions first, and come back to the c code later...

**Comment by exowanderer** [comment] 2018-12-19 13:09
Hi @lkreidberg and @kevin218, 

I was away on vacation (with babies) for the last week, so I missed this whole conversation.

I'll check into it later today and get back to you. 

Thank you for the info. 

Note: when I run `python $HOME/path/to/POET/code/lib/models_c/UnitTest.py`, I receive no `FAIL to load` or `FAIL` errors at all. So I may not be able to assess the issue.

@lkreidberg:

(1) would you mind cloning a fresh copy of the repo in a new directory (assuming that you used `git pull` before only) and see if the `UnitTest.py` works or has the same issues?

I know that `git pull` should work; but I want to try starting fresh first.

(2) I am using `gcc` for my compiler.  Could you check what `sysconfig` reports for your CC flag, please?

```python
import sysconfig
print(sysconfig.get_config_vars()['CC'])
```

My output only says `gcc`.


(3) When I run 

```bash
bash build.sh clean
CC=/usr/bin/clang CXX=/usr/bin/clang++ bash build.sh
python UnitTest.py
```

I also get no errors. Note that I am guessing `CC=/usr/bin/clang CXX=/usr/bin/clang++` is correct because of unrelated stackoverflow entries that I read before.

Thank you,

Jonathan

PS: I just found `sysconfig` now by googling our issue. So I am comfortable that it is giving me the correct information; but not what the full implication is for our situation.

**Comment by kevin218** [comment] 2019-03-04 20:42
I'm closing this issue, but leaving as a note to others that they can use `pbilinint` and `pnnint` instead of `bilinint` and `nnint` if they can't get the latter two functions to compile in C.  These are the original Python versions of the code.

**Closed as completed by kevin218** 2019-03-04 20:42 UTC
